name: Trigger auto deployment for typingmind-ca-plugins-server

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/typingmind-ca-plugins-server-AutoDeployTrigger-52764832-0b12-4df9-ac5b-4edd54736065.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.TYPINGMINDCAPLUGINSSERVER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: slap0ai0projects.azurecr.io
          registryUsername: ${{ secrets.TYPINGMINDCAPLUGINSSERVER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TYPINGMINDCAPLUGINSSERVER_REGISTRY_PASSWORD }}
          containerAppName: typingmind-ca-plugins-server
          resourceGroup: typingmind-plugins-server
          imageToBuild: slap0ai0projects.azurecr.io/typingmind-ca-plugins-server:${{ github.sha }}
          
            

     

